package ph.txtdis.type;

public enum BillableType {
	BAD_ORDER, //
	DELIVERY_LIST, //
	DELIVERY_REPORT, //
	DELIVERY_RETURN, //
	DOWNLOAD, //
	EX_TRUCK, //
	INVOICE, //
	LOAD_MANIFEST, //
	ORDER_CONFIRMATION, //
	PURCHASE_ORDER, //
	PURCHASE_RECEIPT, //
	RETURN_ORDER, //
	REMITTANCE, //
	SALES_ORDER, //
	SALES_RETURN, //
	SIV, //
	STOCK_TAKE, //
	STOCK_TAKE_RECONCILIATION, //
	UPLOAD;
}
