package ph.txtdis.type;

public enum ModuleType {
	BAD_ORDER, //
	CASH_ADVANCE, //
	DELIVERY_LIST, //
	DELIVERY_REPORT, //
	DELIVERY_RETURN, //
	DELIVERY_TO_PURCHASE_ORDER, //
	DELIVERY_TO_SALES_ORDER, //
	DOWNLOAD, //
	EX_TRUCK, //
	INVOICE, //
	LOAD_MANIFEST, //
	LOAD_OUT, //
	LOAD_IN, //
	ORDER_CONFIRMATION, //
	PURCHASE_BILLING, //
	PURCHASE_ORDER, //
	PURCHASE_PAYMENT, //
	PURCHASE_RECEIPT, //
	RETURN_ORDER, //
	REMITTANCE, //
	SALES_BILLING, //
	SALES_ORDER, //
	SALES_RETURN, //
	SIV, //
	STOCK_TAKE, //
	STOCK_TAKE_RECONCILIATION, //
	UPLOAD;
}
