package ph.txtdis.type;

public enum ScriptType {
	BILLING_APPROVAL, // 0
	CREDIT_APPROVAL, // 1
	CUSTOMER_DISCOUNT_APPROVAL, // 2
	DEPOSIT, // 3
	FUND_TRANSFER, // 4
	PAYMENT_VALIDATION, // 5
	PRICE_APPROVAL, // 6
	RETURN_PAYMENT, // 7
	VERSION_UPDATE, // 8
	VOLUME_DISCOUNT_APPROVAL; // 9
}
